import type { Stock, Investor, PricingPlan, Testimonial, FAQItem, MarketIndex, ScoringCriterion } from '@/types';

export const mockStocks: Stock[] = [
  {
    ticker: 'AAPL',
    name: 'Apple Inc.',
    price: 195.89,
    change: 2.45,
    changePercent: 1.27,
    marketCap: 3050000000000,
    peRatio: 30.2,
    pbRatio: 48.5,
    psRatio: 7.8,
    dividendYield: 0.52,
    sector: 'Technology',
    score: 78,
    signal: 'buy',
    sparklineData: [190, 192, 191, 193, 194, 193, 195, 194, 196, 195.89],
    volume: 54200000,
    fiftyTwoWeekHigh: 199.62,
    fiftyTwoWeekLow: 164.08,
    avgVolume: 58000000,
  },
  {
    ticker: 'MSFT',
    name: 'Microsoft Corporation',
    price: 420.55,
    change: 5.32,
    changePercent: 1.28,
    marketCap: 3120000000000,
    peRatio: 36.8,
    pbRatio: 12.4,
    psRatio: 13.2,
    dividendYield: 0.68,
    sector: 'Technology',
    score: 85,
    signal: 'buy',
    sparklineData: [412, 414, 413, 416, 415, 418, 417, 419, 418, 420.55],
    volume: 22100000,
    fiftyTwoWeekHigh: 468.35,
    fiftyTwoWeekLow: 362.90,
    avgVolume: 25000000,
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    price: 175.98,
    change: -1.23,
    changePercent: -0.69,
    marketCap: 2180000000000,
    peRatio: 25.4,
    pbRatio: 6.8,
    psRatio: 5.9,
    dividendYield: 0.45,
    sector: 'Technology',
    score: 82,
    signal: 'buy',
    sparklineData: [178, 177, 176, 177, 176, 175, 176, 175, 176, 175.98],
    volume: 18900000,
    fiftyTwoWeekHigh: 191.75,
    fiftyTwoWeekLow: 129.40,
    avgVolume: 22000000,
  },
  {
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    price: 178.35,
    change: 3.12,
    changePercent: 1.78,
    marketCap: 1850000000000,
    peRatio: 58.9,
    pbRatio: 8.2,
    psRatio: 2.8,
    dividendYield: 0,
    sector: 'Consumer Cyclical',
    score: 71,
    signal: 'hold',
    sparklineData: [173, 174, 173, 175, 174, 176, 175, 177, 176, 178.35],
    volume: 38900000,
    fiftyTwoWeekHigh: 201.20,
    fiftyTwoWeekLow: 118.35,
    avgVolume: 42000000,
  },
  {
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    price: 248.50,
    change: -8.75,
    changePercent: -3.40,
    marketCap: 790000000000,
    peRatio: 72.5,
    pbRatio: 9.8,
    psRatio: 7.2,
    dividendYield: 0,
    sector: 'Consumer Cyclical',
    score: 45,
    signal: 'hold',
    sparklineData: [258, 256, 254, 255, 253, 251, 252, 250, 249, 248.50],
    volume: 98700000,
    fiftyTwoWeekHigh: 299.29,
    fiftyTwoWeekLow: 152.37,
    avgVolume: 105000000,
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corporation',
    price: 875.28,
    change: 15.42,
    changePercent: 1.79,
    marketCap: 2150000000000,
    peRatio: 72.8,
    pbRatio: 52.3,
    psRatio: 37.5,
    dividendYield: 0.03,
    sector: 'Technology',
    score: 68,
    signal: 'hold',
    sparklineData: [856, 860, 858, 862, 865, 863, 868, 870, 872, 875.28],
    volume: 45200000,
    fiftyTwoWeekHigh: 974.00,
    fiftyTwoWeekLow: 262.20,
    avgVolume: 48000000,
  },
  {
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    price: 505.68,
    change: 7.89,
    changePercent: 1.58,
    marketCap: 1290000000000,
    peRatio: 26.4,
    pbRatio: 8.1,
    psRatio: 9.8,
    dividendYield: 0.42,
    sector: 'Technology',
    score: 88,
    signal: 'buy',
    sparklineData: [495, 497, 496, 498, 500, 499, 502, 503, 504, 505.68],
    volume: 15200000,
    fiftyTwoWeekHigh: 544.23,
    fiftyTwoWeekLow: 279.40,
    avgVolume: 18000000,
  },
  {
    ticker: 'BRK.B',
    name: 'Berkshire Hathaway Inc.',
    price: 412.15,
    change: 1.85,
    changePercent: 0.45,
    marketCap: 890000000000,
    peRatio: 9.2,
    pbRatio: 1.5,
    psRatio: 2.1,
    dividendYield: 0,
    sector: 'Financials',
    score: 91,
    signal: 'buy',
    sparklineData: [408, 409, 410, 409, 411, 410, 411, 412, 411, 412.15],
    volume: 3200000,
    fiftyTwoWeekHigh: 430.92,
    fiftyTwoWeekLow: 338.89,
    avgVolume: 3800000,
  },
  {
    ticker: 'JPM',
    name: 'JPMorgan Chase & Co.',
    price: 195.42,
    change: -0.58,
    changePercent: -0.30,
    marketCap: 560000000000,
    peRatio: 11.8,
    pbRatio: 1.6,
    psRatio: 3.2,
    dividendYield: 2.35,
    sector: 'Financials',
    score: 86,
    signal: 'buy',
    sparklineData: [197, 196, 196, 195, 196, 195, 195, 196, 195, 195.42],
    volume: 8900000,
    fiftyTwoWeekHigh: 200.94,
    fiftyTwoWeekLow: 135.19,
    avgVolume: 11000000,
  },
  {
    ticker: 'V',
    name: 'Visa Inc.',
    price: 285.78,
    change: 2.15,
    changePercent: 0.76,
    marketCap: 620000000000,
    peRatio: 32.5,
    pbRatio: 13.8,
    psRatio: 16.2,
    dividendYield: 0.72,
    sector: 'Financials',
    score: 79,
    signal: 'buy',
    sparklineData: [282, 283, 282, 284, 283, 285, 284, 285, 284, 285.78],
    volume: 4200000,
    fiftyTwoWeekHigh: 290.96,
    fiftyTwoWeekLow: 227.68,
    avgVolume: 5500000,
  },
  {
    ticker: 'WMT',
    name: 'Walmart Inc.',
    price: 165.32,
    change: 0.89,
    changePercent: 0.54,
    marketCap: 445000000000,
    peRatio: 25.8,
    pbRatio: 5.9,
    psRatio: 0.72,
    dividendYield: 1.38,
    sector: 'Consumer Defensive',
    score: 74,
    signal: 'hold',
    sparklineData: [163, 164, 164, 165, 164, 165, 165, 166, 165, 165.32],
    volume: 5600000,
    fiftyTwoWeekHigh: 169.94,
    fiftyTwoWeekLow: 136.09,
    avgVolume: 6800000,
  },
  {
    ticker: 'JNJ',
    name: 'Johnson & Johnson',
    price: 152.18,
    change: -1.24,
    changePercent: -0.81,
    marketCap: 366000000000,
    peRatio: 15.2,
    pbRatio: 5.1,
    psRatio: 3.8,
    dividendYield: 3.12,
    sector: 'Healthcare',
    score: 72,
    signal: 'hold',
    sparklineData: [154, 153, 153, 152, 153, 152, 152, 151, 152, 152.18],
    volume: 6200000,
    fiftyTwoWeekHigh: 175.97,
    fiftyTwoWeekLow: 143.13,
    avgVolume: 7800000,
  },
];

export const investors: Investor[] = [
  {
    id: 'buffett',
    name: 'Warren Buffett',
    title: 'The Oracle of Omaha',
    description: 'Legendary value investor known for long-term holdings in quality companies with durable competitive advantages.',
    strategy: 'Value investing with focus on companies with strong moats, consistent earnings, and reasonable valuations.',
    topHoldings: [
      { ticker: 'AAPL', name: 'Apple Inc.', allocation: 50.2 },
      { ticker: 'BAC', name: 'Bank of America', allocation: 8.9 },
      { ticker: 'AXP', name: 'American Express', allocation: 7.2 },
      { ticker: 'KO', name: 'Coca-Cola', allocation: 6.8 },
      { ticker: 'CVX', name: 'Chevron', allocation: 5.4 },
    ],
    allocation: {
      'Technology': 52,
      'Financials': 25,
      'Consumer Defensive': 12,
      'Energy': 8,
      'Other': 3,
    },
    color: '#8B5CF6',
  },
  {
    id: 'dalio',
    name: 'Ray Dalio',
    title: 'Founder of Bridgewater',
    description: 'Creator of the All Weather portfolio strategy focused on risk parity and diversification across asset classes.',
    strategy: 'Risk parity approach with balanced allocation across stocks, bonds, commodities, and gold.',
    topHoldings: [
      { ticker: 'SPY', name: 'SPDR S&P 500 ETF', allocation: 30 },
      { ticker: 'TLT', name: 'iShares 20+ Year Treasury', allocation: 40 },
      { ticker: 'GLD', name: 'SPDR Gold Trust', allocation: 7.5 },
      { ticker: 'DBC', name: 'Invesco DB Commodity Tracking', allocation: 7.5 },
      { ticker: 'VGIT', name: 'Vanguard Intermediate Treasury', allocation: 15 },
    ],
    allocation: {
      'US Stocks': 30,
      'Long-term Bonds': 40,
      'Intermediate Bonds': 15,
      'Commodities': 7.5,
      'Gold': 7.5,
    },
    color: '#06B6D4',
  },
  {
    id: 'wood',
    name: 'Cathie Wood',
    title: 'ARK Invest CEO',
    description: 'Innovation-focused investor betting on disruptive technologies that will shape the future.',
    strategy: 'High-growth innovation investing in genomics, AI, robotics, energy storage, and blockchain.',
    topHoldings: [
      { ticker: 'TSLA', name: 'Tesla Inc.', allocation: 9.8 },
      { ticker: 'COIN', name: 'Coinbase Global', allocation: 7.2 },
      { ticker: 'ROKU', name: 'Roku Inc.', allocation: 6.5 },
      { ticker: 'SQ', name: 'Block Inc.', allocation: 5.8 },
      { ticker: 'ZM', name: 'Zoom Video', allocation: 5.2 },
    ],
    allocation: {
      'Technology': 45,
      'Healthcare': 25,
      'Communication': 15,
      'Financials': 10,
      'Other': 5,
    },
    color: '#EC4899',
  },
  {
    id: 'lynch',
    name: 'Peter Lynch',
    title: 'Fidelity Magellan',
    description: 'Famous for "invest in what you know" philosophy and finding growth at reasonable prices.',
    strategy: 'GARP (Growth at Reasonable Price) with emphasis on understanding the business.',
    topHoldings: [
      { ticker: 'PG', name: 'Procter & Gamble', allocation: 12 },
      { ticker: 'WMT', name: 'Walmart Inc.', allocation: 10 },
      { ticker: 'HD', name: 'Home Depot', allocation: 9 },
      { ticker: 'MCD', name: "McDonald's", allocation: 8 },
      { ticker: 'NKE', name: 'Nike Inc.', allocation: 7 },
    ],
    allocation: {
      'Consumer Defensive': 35,
      'Consumer Cyclical': 25,
      'Healthcare': 20,
      'Technology': 15,
      'Other': 5,
    },
    color: '#10B981',
  },
  {
    id: 'graham',
    name: 'Benjamin Graham',
    title: 'Father of Value Investing',
    description: 'Pioneer of value investing with emphasis on margin of safety and fundamental analysis.',
    strategy: 'Deep value investing with strict criteria for low P/E, low P/B, and strong balance sheets.',
    topHoldings: [
      { ticker: 'BRK.B', name: 'Berkshire Hathaway', allocation: 15 },
      { ticker: 'JPM', name: 'JPMorgan Chase', allocation: 12 },
      { ticker: 'XOM', name: 'Exxon Mobil', allocation: 10 },
      { ticker: 'CVX', name: 'Chevron', allocation: 9 },
      { ticker: 'INTC', name: 'Intel Corp', allocation: 8 },
    ],
    allocation: {
      'Financials': 30,
      'Energy': 25,
      'Technology': 20,
      'Industrials': 15,
      'Other': 10,
    },
    color: '#F59E0B',
  },
  {
    id: 'soros',
    name: 'George Soros',
    title: 'The Man Who Broke the Bank',
    description: 'Legendary hedge fund manager known for macroeconomic trades and the theory of reflexivity.',
    strategy: 'Global macro investing based on economic trends and currency movements.',
    topHoldings: [
      { ticker: 'QQQ', name: 'Invesco QQQ Trust', allocation: 18 },
      { ticker: 'SPY', name: 'SPDR S&P 500 ETF', allocation: 15 },
      { ticker: 'IWM', name: 'iShares Russell 2000', allocation: 12 },
      { ticker: 'EEM', name: 'iShares MSCI Emerging Markets', allocation: 10 },
      { ticker: 'TLT', name: 'iShares 20+ Year Treasury', allocation: 8 },
    ],
    allocation: {
      'US Large Cap': 35,
      'US Small Cap': 15,
      'International': 20,
      'Fixed Income': 20,
      'Cash': 10,
    },
    color: '#EF4444',
  },
  {
    id: 'druckenmiller',
    name: 'Stanley Druckenmiller',
    title: 'Duquesne Capital',
    description: 'One of the most successful hedge fund managers with 30 years of positive returns.',
    strategy: 'Concentrated bets on high-conviction ideas with flexible long/short approach.',
    topHoldings: [
      { ticker: 'NVDA', name: 'NVIDIA Corp', allocation: 14 },
      { ticker: 'MSFT', name: 'Microsoft', allocation: 12 },
      { ticker: 'GOOGL', name: 'Alphabet', allocation: 10 },
      { ticker: 'AMZN', name: 'Amazon', allocation: 9 },
      { ticker: 'META', name: 'Meta Platforms', allocation: 8 },
    ],
    allocation: {
      'Technology': 55,
      'Communication': 20,
      'Consumer': 15,
      'Other': 10,
    },
    color: '#3B82F6',
  },
  {
    id: 'ackman',
    name: 'Bill Ackman',
    title: 'Pershing Square',
    description: 'Activist investor known for concentrated bets and pushing for corporate change.',
    strategy: 'High-conviction, concentrated investments in quality businesses with moats.',
    topHoldings: [
      { ticker: 'HLT', name: 'Hilton Worldwide', allocation: 18 },
      { ticker: 'CMG', name: 'Chipotle Mexican Grill', allocation: 16 },
      { ticker: 'QSR', name: 'Restaurant Brands', allocation: 14 },
      { ticker: 'LOW', name: "Lowe's Companies", allocation: 12 },
      { ticker: 'GOOGL', name: 'Alphabet', allocation: 10 },
    ],
    allocation: {
      'Consumer Discretionary': 50,
      'Technology': 20,
      'Industrials': 15,
      'Real Estate': 15,
    },
    color: '#14B8A6',
  },
  {
    id: 'templeton',
    name: 'John Templeton',
    title: 'Global Value Pioneer',
    description: 'Pioneer of global investing who sought value in overlooked international markets.',
    strategy: 'Contrarian global value investing in unpopular markets and sectors.',
    topHoldings: [
      { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets', allocation: 25 },
      { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets', allocation: 20 },
      { ticker: 'IEFA', name: 'iShares Core MSCI EAFE', allocation: 18 },
      { ticker: 'SPY', name: 'SPDR S&P 500 ETF', allocation: 15 },
      { ticker: 'VXUS', name: 'Vanguard Total International Stock', allocation: 12 },
    ],
    allocation: {
      'International Developed': 45,
      'Emerging Markets': 25,
      'US Stocks': 20,
      'Other': 10,
    },
    color: '#8B5CF6',
  },
  {
    id: 'marks',
    name: 'Howard Marks',
    title: 'Oaktree Capital',
    description: 'Credit investor known for his memos on market cycles and distressed debt investing.',
    strategy: 'Contrarian credit and distressed debt investing with focus on risk control.',
    topHoldings: [
      { ticker: 'PGHY', name: 'Invesco PGHY', allocation: 20 },
      { ticker: 'SJNK', name: 'SPDR Bloomberg Short Term High Yield', allocation: 18 },
      { ticker: 'BKLN', name: 'Invesco Senior Loan ETF', allocation: 15 },
      { ticker: 'HYG', name: 'iShares iBoxx High Yield', allocation: 12 },
      { ticker: 'SPY', name: 'SPDR S&P 500 ETF', allocation: 10 },
    ],
    allocation: {
      'High Yield Bonds': 40,
      'Senior Loans': 25,
      'Distressed Debt': 15,
      'Equities': 15,
      'Cash': 5,
    },
    color: '#F97316',
  },
  {
    id: 'simons',
    name: 'Jim Simons',
    title: 'Renaissance Technologies',
    description: 'Mathematician who pioneered quantitative trading using algorithms and pattern recognition.',
    strategy: 'Quantitative systematic trading based on statistical arbitrage and pattern recognition.',
    topHoldings: [
      { ticker: 'NVDA', name: 'NVIDIA Corp', allocation: 8 },
      { ticker: 'META', name: 'Meta Platforms', allocation: 7 },
      { ticker: 'AMZN', name: 'Amazon', allocation: 7 },
      { ticker: 'GOOGL', name: 'Alphabet', allocation: 6 },
      { ticker: 'MSFT', name: 'Microsoft', allocation: 6 },
    ],
    allocation: {
      'Technology': 35,
      'Healthcare': 20,
      'Consumer': 15,
      'Financials': 15,
      'Other': 15,
    },
    color: '#6366F1',
  },
  {
    id: 'icahn',
    name: 'Carl Icahn',
    title: 'Icahn Enterprises',
    description: 'Activist investor known for aggressive corporate raiding and shareholder activism.',
    strategy: 'Activist investing to unlock value through corporate governance changes.',
    topHoldings: [
      { ticker: 'IEP', name: 'Icahn Enterprises', allocation: 55 },
      { ticker: 'CVI', name: 'CVR Energy', allocation: 12 },
      { ticker: 'OXY', name: 'Occidental Petroleum', allocation: 10 },
      { ticker: 'SWX', name: 'Southwest Gas', allocation: 8 },
      { ticker: 'XRX', name: 'Xerox Holdings', allocation: 5 },
    ],
    allocation: {
      'Energy': 35,
      'Industrials': 25,
      'Utilities': 20,
      'Technology': 15,
      'Other': 5,
    },
    color: '#DC2626',
  },
];

export const pricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Get started with basic stock screening',
    monthlyPrice: 0,
    annualPrice: 0,
    features: [
      'Basic stock screener',
      '5 stock analyses per day',
      'Delayed market data (15 min)',
      'Default scoring weights',
      'Email support',
    ],
    cta: 'Get Started Free',
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'For serious investors who want an edge',
    monthlyPrice: 49,
    annualPrice: 39,
    features: [
      'Advanced stock screener',
      'Unlimited stock analyses',
      'Real-time market data',
      'Custom scoring weights',
      'Portfolio tracking',
      'Priority email support',
    ],
    highlighted: true,
    cta: 'Start Free Trial',
  },
  {
    id: 'elite',
    name: 'Elite',
    description: 'Professional-grade tools for power users',
    monthlyPrice: 99,
    annualPrice: 79,
    features: [
      'Everything in Pro',
      'Famous investor portfolios',
      'API access',
      'Advanced analytics',
      'Custom alerts',
      'Priority phone support',
      'Dedicated account manager',
    ],
    cta: 'Contact Sales',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Michael Rodriguez',
    role: 'Day Trader',
    content: 'The scoring system is incredibly transparent. I can see exactly why a stock gets its rating, and the customizable weights let me align it with my strategy.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Sarah Lin',
    role: 'Long-term Investor',
    content: 'Mimicking Buffett\'s portfolio within my budget has been a game-changer. I\'ve seen consistent returns while learning from the best.',
    rating: 5,
  },
  {
    id: '3',
    name: 'David Kim',
    role: 'Portfolio Manager',
    content: 'Best investment tool I\'ve ever used. The real-time data is crucial for my decisions, and the interface is beautiful and intuitive.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Emily Chen',
    role: 'Retail Investor',
    content: 'I started with the free plan and upgraded to Pro within a week. The difference in data quality and analysis depth is remarkable.',
    rating: 5,
  },
  {
    id: '5',
    name: 'James Wilson',
    role: 'Financial Advisor',
    content: 'I recommend StockWise Pro to all my clients. The open-box scoring builds trust, and the portfolio tools are exceptional.',
    rating: 5,
  },
];

export const faqItems: FAQItem[] = [
  {
    id: '1',
    question: 'How does the scoring system work?',
    answer: 'Our scoring system evaluates stocks across five key criteria: Valuation (P/E, P/B, P/S ratios), Profitability (ROE, ROA, margins), Growth (revenue and EPS growth), Financial Health (debt ratios, liquidity), and Momentum (price performance). Each criterion receives a sub-score from 0-100, which is then weighted and combined into a final score. Scores above 70 indicate a BUY signal, 40-69 indicate HOLD, and below 40 suggest SELL.',
  },
  {
    id: '2',
    question: 'Can I customize the scoring weights?',
    answer: 'Yes! Pro and Elite subscribers can fully customize the scoring weights to match their investment strategy. You can adjust the importance of each criterion using our intuitive slider interface. Save multiple weight presets for different strategies (e.g., value-focused, growth-focused, balanced).',
  },
  {
    id: '3',
    question: 'Which investors\' portfolios can I mimic?',
    answer: 'Elite subscribers can mimic portfolios from legendary investors including Warren Buffett (value investing), Ray Dalio (all-weather portfolio), Cathie Wood (innovation-focused), Peter Lynch (GARP strategy), and Benjamin Graham (deep value). We regularly add new investor profiles based on user requests.',
  },
  {
    id: '4',
    question: 'Is the data real-time?',
    answer: 'Free users receive delayed data (15-minute delay). Pro and Elite subscribers get real-time market data during trading hours. All plans have access to historical data and after-hours pricing.',
  },
  {
    id: '5',
    question: 'How do I cancel my subscription?',
    answer: 'You can cancel your subscription at any time from your account settings. Your access will continue until the end of your current billing period. We also offer a 30-day money-back guarantee for new subscribers.',
  },
];

export const marketIndices: MarketIndex[] = [
  { symbol: 'SPX', name: 'S&P 500', price: 5950.32, change: 42.15, changePercent: 0.71 },
  { symbol: 'NDX', name: 'NASDAQ', price: 20850.45, change: 185.32, changePercent: 0.90 },
  { symbol: 'DJI', name: 'Dow Jones', price: 43450.28, change: 125.48, changePercent: 0.29 },
  { symbol: 'RUT', name: 'Russell 2000', price: 2285.64, change: 18.92, changePercent: 0.83 },
];

export const defaultScoringCriteria: ScoringCriterion[] = [
  {
    id: 'valuation',
    name: 'Valuation',
    description: 'Measures if the stock is priced fairly relative to its fundamentals',
    weight: 25,
    metrics: [
      { id: 'pe', name: 'P/E Ratio', value: 15, maxValue: 30, score: 75 },
      { id: 'pb', name: 'P/B Ratio', value: 3, maxValue: 5, score: 70 },
      { id: 'ps', name: 'P/S Ratio', value: 4, maxValue: 10, score: 80 },
    ],
  },
  {
    id: 'profitability',
    name: 'Profitability',
    description: 'Evaluates how efficiently the company generates profits',
    weight: 25,
    metrics: [
      { id: 'roe', name: 'Return on Equity', value: 18, maxValue: 25, score: 85 },
      { id: 'roa', name: 'Return on Assets', value: 12, maxValue: 20, score: 75 },
      { id: 'margin', name: 'Profit Margin', value: 22, maxValue: 30, score: 80 },
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    description: 'Assesses the company\'s revenue and earnings growth trajectory',
    weight: 20,
    metrics: [
      { id: 'rev_growth', name: 'Revenue Growth', value: 15, maxValue: 25, score: 70 },
      { id: 'eps_growth', name: 'EPS Growth', value: 18, maxValue: 30, score: 75 },
    ],
  },
  {
    id: 'financialHealth',
    name: 'Financial Health',
    description: 'Analyzes the company\'s balance sheet strength and debt levels',
    weight: 15,
    metrics: [
      { id: 'debt_equity', name: 'Debt/Equity', value: 0.5, maxValue: 1, score: 85 },
      { id: 'current_ratio', name: 'Current Ratio', value: 2.1, maxValue: 3, score: 80 },
    ],
  },
  {
    id: 'momentum',
    name: 'Momentum',
    description: 'Tracks price performance and technical indicators',
    weight: 15,
    metrics: [
      { id: 'price_perf', name: 'Price Performance', value: 25, maxValue: 50, score: 65 },
      { id: 'rsi', name: 'RSI', value: 55, maxValue: 100, score: 70 },
    ],
  },
];

export const sectors = [
  'Technology',
  'Healthcare',
  'Financials',
  'Consumer Cyclical',
  'Consumer Defensive',
  'Industrials',
  'Energy',
  'Materials',
  'Real Estate',
  'Utilities',
  'Communication',
];
